### ISSUE TITLE
xOffset in config not respected

### ISSUE THREAD

**Issue by HipHopHuman** [Tfarcenim/SmartHUD#1]
Hi! First off, thanks for forking the mod. I was missing playing with this feature. I'm having an issue with the xOffset config not being respected. I've set it to  `100`, `500`, `1000`, `-10000` but it always remains in the same place - opposite the offhand slot. This conflicts visually with Quark's armor ticker.

I'm playing in 1.15.2 and I also have "Console Experience" installed which may be messing with this, as it shifts the hotbar up the screen a few pixels. I'm setting up a vanilla profile at the moment to test if the xOffset config works without Console Experience installed.

I'm not sure if there's anything else I can provide to make debugging easier - would a debug.log even help?

**Comment by Tfarcenim** [comment]
Fixed in 1.16.3
