### ISSUE TITLE
Any plan for future Fabric compatibility?

### ISSUE THREAD

**Issue by ghost** [Tfarcenim/SmartHUD#4]
I stared using [Fabric](https://fabricmc.net/) instead of Forge because of its faster release rate and because I mainly use client side mods for QoL stuff. Most of the stuff I would find on Forge is also compatible or ported under different name to Fabric and since your project revived this neat mod I was wondering if you knew of Fabric or if you already considered compatibility with it for possible future releases

**Comment by Tfarcenim** [comment]
I have plans for Fabric eventually, but time is not on my side.
